# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-24 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20171020_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='ArticleCategory',
        ),
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name_plural': 'article categories'},
        ),
    ]
