# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-22 09:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerWithUsSnippet',
            fields=[
                ('calltoactionsnippet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='utils.CallToActionSnippet')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=18)),
            ],
            options={
                'abstract': False,
            },
            bases=('utils.calltoactionsnippet',),
        ),
    ]
