# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_partnerwithussnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionsnippet',
            name='summary',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=250, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='calltoactionsnippet',
            name='title',
            field=models.CharField(max_length=80),
        ),
    ]
