# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('utils', '0003_auto_20171017_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=80)),
                ('statistic_value', models.CharField(help_text="The value of the statistic (e.g. the '85' in '85%')", max_length=4, verbose_name='Value')),
                ('statistic_units', models.CharField(help_text="The units of the statistic (e.g. the '%' in '85%')", max_length=4, verbose_name='Units')),
                ('description', wagtail.wagtailcore.fields.RichTextField(blank=True, max_length=80, verbose_name='Description')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
