# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0004_statistic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoactionsnippet',
            name='summary',
            field=models.CharField(blank=True, max_length=80, verbose_name='Description'),
        ),
    ]
