# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0006_auto_20171108_1518'),
        ('utils', '0006_custommedia'),
    ]

    operations = [
    ]
