# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-09 14:21
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_merge_20171109_1001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistic',
            name='statistic_units',
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='statistic_value',
        ),
        migrations.AlterField(
            model_name='statistic',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text="The statistic. For example, '66%% of girls complete primary school'", max_length=255, verbose_name='Description'),
        ),
    ]
