# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_auto_20171114_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='citation_text',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
