# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('utils', '0010_statistic_citation_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='default_sharing_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
