# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 11:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0012_statisticcustomisableheading'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoactionsnippet',
            name='link_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
