# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-19 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('wagtailcore', '0040_page_draft_title'),
        ('utils', '0013_p1_changes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullWidthMediaAndTextSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('text', wagtail.wagtailcore.fields.RichTextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FullWidthMediaAndTextSnippetCustomisableHeading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('background_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('heading_hex', models.CharField(blank=True, max_length=7, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('media', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_customisation', to='utils.FullWidthMediaAndTextSnippet')),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
    ]
