# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0013_calltoactionsnippet_link_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='cms_title',
            field=models.CharField(blank=True, help_text='Snippet CMS title only viewable in admin area', max_length=225, null=True),
        ),
    ]
