# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-21 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0014_add_full_width_media_snippet'),
        ('utils', '0014_partner_cta_rm_contacts'),
    ]

    operations = [
    ]
