# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('images', '0001_initial'),
        ('utils', '0014_partner_cta_rm_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerWithUsSnippetNew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_url', models.URLField(blank=True)),
                ('link_text', models.CharField(blank=True, max_length=255)),
                ('link_email', models.EmailField(blank=True, max_length=254)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('summary', models.CharField(blank=True, max_length=80, verbose_name='Description')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('link_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='PartnerWithUsSnippet',
            new_name='PartnerWithUsSnippetOld',
        ),
        migrations.AlterField(
            model_name='calltoactionsnippet',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
