# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 16:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_auto_20180126_1658'),
    ]

    operations = [
    ]
