# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_brandingsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandingsettings',
            name='footer_text',
            field=models.TextField(blank=True),
        ),
    ]
