# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-23 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0015_merge_20180221_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fullwidthmediaandtextsnippet',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
