# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 16:22
from __future__ import unicode_literals

from django.db import migrations


def create_default_site_brandingsettings(apps, schema_editor):
    BrandingSettings = apps.get_model('utils.BrandingSettings')
    Site = apps.get_model('wagtailcore.Site')

    default_site = Site.objects.get(is_default_site=True)
    BrandingSettings.objects.update_or_create(
        site=default_site,
        defaults={
            'footer_text': "Company No.07516619\r\n\r\nCharity No.1141155",
        }
    )


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_brandingsettings_footer_text'),
    ]

    operations = [
        migrations.RunPython(create_default_site_brandingsettings, do_nothing)
    ]
