# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0017_brandingsettings_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='facebook_page_handle',
            field=models.CharField(blank=True, help_text='Your Facebook page handle. For example, if your Facebook page URL is "https://www.facebook.com/girleffect/" then this field should be set to "girleffect" (case sensitive)', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Your Instagram handle. For example, if your Instagram URL is "https://www.instagram.com/girleffect/" then this field should be set to "girleffect" (case sensitive)', max_length=255),
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin_handle',
            field=models.CharField(blank=True, help_text='Your LinkedIn handle. For example, if your LinkedIn URL is "https://www.linkedin.com/company/girleffect/" then this field should be set to "girleffect" (case sensitive)', max_length=255),
        ),
    ]
