# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 16:51
from __future__ import unicode_literals

from django.db import migrations


def set_default_site_handles(apps, schema_editor):
    SocialMediaSettings = apps.get_model('utils.SocialMediaSettings')

    SocialMediaSettings.objects.filter(site__is_default_site=True).update(
        facebook_page_handle='girleffect',
        instagram_handle='girleffect',
        linkedin_handle='girleffect',
    )


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0018_socialmediasettings_handle_fields'),
    ]

    operations = [
        migrations.RunPython(set_default_site_handles, do_nothing),
    ]
