# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 09:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0016_make_full_width_media_and_text_snippet_title_optional'),
        ('utils', '0019_socialmediasettings_handle_fields_initial_data'),
    ]

    operations = [
    ]
