# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0020_merge_20180423_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='youtube_handle',
            field=models.CharField(blank=True, help_text='Your Youtube handle. For example, if your Youtube URL is "https://www.youtube.com/user/girleffect/" then this field should be set to "girleffect" (case sensitive)', max_length=255),
        ),
    ]
