# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0022_analyticssettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='Id will be like GTM-PQ8TM6V', max_length=20),
        ),
    ]
