# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 10:03
from __future__ import unicode_literals

from django.db import migrations


def set_default_site_youtube_handle(apps, schema_editor):
    SocialMediaSettings = apps.get_model('utils.SocialMediaSettings')

    SocialMediaSettings.objects.filter(site__is_default_site=True).update(
        youtube_handle='girleffect',
    )


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0023_auto_20180423_1039'),
    ]

    operations = [
        migrations.RunPython(set_default_site_youtube_handle, do_nothing),
    ]
