# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 10:06
from __future__ import unicode_literals

from django.db import migrations


def set_default_site_google_tag_id(apps, schema_editor):
    AnalyticsSettings = apps.get_model('utils.AnalyticsSettings')

    AnalyticsSettings.objects.filter(site__is_default_site=True).update(
        google_tag_manager_id='GTM-PQ8TM6V',
    )


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0024_socialmediasettings_youtube_handle_field_initial_data'),
    ]

    operations = [
        migrations.RunPython(set_default_site_google_tag_id, do_nothing),
    ]
