# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-01 09:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0021_merge_20180425_1124'),
        ('utils', '0025_analyticssettings_google_tag_manager_initial_data'),
    ]

    operations = [
    ]
