# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-03 06:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0025_analyticssettings_google_tag_manager_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analyticssettings',
            name='google_tag_manager_id',
            field=models.CharField(blank=True, help_text='Your GTM ID is found on the Admin page of your GTM account.', max_length=20),
        ),
    ]
