# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-05-03 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0026_merge_20180501_1057'),
        ('utils', '0026_auto_20180503_0740'),
    ]

    operations = [
    ]
