# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('news', '0002_auto_20170830_1557')]

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Not currently shown to the end user but may be in the future.')),
            ],
            options={
                'verbose_name_plural': 'news categories',
            },
        ),
        migrations.AlterField(
            model_name='newspagecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='articles.NewsCategory'),
        ),
    ]
