# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-06 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_auto_20171102_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlepage',
            name='author',
            field=models.CharField(blank=True, help_text="Optional Author name. Will default to 'Girl Effect Team' if empty.", max_length=255),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='introduction',
            field=models.TextField(blank=True, max_length=350),
        ),
    ]
