# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0024_articlepage_hero_image'),
        ('articles', '0024_auto_20171110_1537'),
    ]

    operations = [
    ]
