# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 10:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0030_auto_20171117_1402'),
        ('articles', '0030_auto_20171117_1423'),
    ]

    operations = [
    ]
