# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_merge_20171120_1012'),
        ('articles', '0031_merge_20171121_1042'),
    ]

    operations = [
    ]
