# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_merge_20171121_1042'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleindex',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='articlepage',
            name='social_title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
