# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-29 15:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_auto_20171127_1323'),
        ('articles', '0036_auto_20171129_1449'),
    ]

    operations = [
    ]
