# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 09:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0036_auto_20171129_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleindex',
            name='heading',
        ),
    ]
