# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-01 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0037_remove_articleindex_heading'),
        ('articles', '0037_merge_20171129_1505'),
    ]

    operations = [
    ]
