# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0038_merge_20171201_1358'),
        ('articles', '0039_auto_20171204_1733'),
    ]

    operations = [
    ]
