# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0041_auto_20180105_1521'),
        ('articles', '0044_add_new_carousel_block_hex'),
    ]

    operations = [
    ]
