# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0046_auto_20180105_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindex',
            name='hero_strapline',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='hero_strapline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
