# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-23 15:08
from __future__ import unicode_literals
import json
from django.db import migrations


def copy_title_to_strapline(apps, schema_editor):
    ArticlePage = apps.get_model('articles', 'ArticlePage')
    for article in ArticlePage.objects.all():
        for revision in article.revisions.all():
            content = json.loads(revision.content_json)

            if 'hero_strapline' and 'title' in content:
                content['hero_strapline'] = content['title']

            revision.content_json = json.dumps(content)
            revision.save()


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0050_hero_strapline_customisation'),
    ]

    operations = [
        migrations.RunPython(copy_title_to_strapline)
    ]
