# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0051_title_strapline_data_migration'),
        ('articles', '0051_article_categories_ordering'),
    ]

    operations = [
    ]
