# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-25 10:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_add_story_block_image_text_overlay'),
        ('articles', '0049_articlecategory_site'),
    ]

    operations = [
    ]
