# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-24 12:49
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0053_add_story_block_image_text_overlay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleindex',
            name='hero_strapline',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Shows text over the hero. If no strapline is entered, no page title will show.', null=True),
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='hero_strapline',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Shows text over the hero. If no strapline is entered, no page title will show.', null=True),
        ),
    ]
