# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0021_auto_20171114_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='standardindex',
            name='hero_heading',
        ),
        migrations.RemoveField(
            model_name='standardpage',
            name='hero_heading',
        ),
        migrations.AddField(
            model_name='standardindex',
            name='hero_strapline',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hero_strapline',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='standardindex',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero Image to be used as full width feature image for page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AlterField(
            model_name='standardpage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero Image to be used as full width feature image for page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
