# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-05 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0028_auto_20171127_1323'),
        ('standardpage', '0029_auto_20171204_1733'),
    ]

    operations = [
    ]
