# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-24 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0037_p1_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardindex',
            name='exclude_from_navigation',
            field=models.BooleanField(default=False, help_text='Check to prevent linking to this page in the navigation and breadcrumbs,            for example if the page is empty.'),
        ),
    ]
