# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0038_hero_strapline_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='standardindex',
            name='hero_strapline_hex',
            field=models.CharField(blank=True, help_text='Add valid hex to change colour of strapline.', max_length=7),
        ),
        migrations.AddField(
            model_name='standardpage',
            name='hero_strapline_hex',
            field=models.CharField(blank=True, help_text='Add valid hex to change colour of strapline.', max_length=7),
        ),
    ]
