# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('standardpage', '0039_hero_strapline_customisation'),
        ('standardpage', '0038_standard_index_nav_checkbox'),
    ]

    operations = [
    ]
