# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0004_countrypage_call_to_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrypagerelatedpage',
            name='page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_relationships', to='solutions.SolutionPage'),
        ),
    ]
