# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-11 14:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0005_auto_20170811_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrypage',
            old_name='introduction',
            new_name='context',
        ),
    ]
