# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-30 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20170811_1305'),
        ('countries', '0007_regionindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPageRelatedSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_solutions', to='solutions.SolutionPage')),
                ('source_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='countries.CountryPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='countrypagerelatedpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='countrypagerelatedpage',
            name='source_page',
        ),
        migrations.DeleteModel(
            name='CountryPageRelatedPage',
        ),
    ]
