# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_auto_20170905_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='sub_title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
