# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 11:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('countries', '0011_countrypage_sub_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='feature_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='feature_video_url',
            field=models.URLField(blank=True),
        ),
    ]
