# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0011_countrypage_sub_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypagerelatedsolution',
            name='page',
        ),
        migrations.RemoveField(
            model_name='countrypagerelatedsolution',
            name='solution_page',
        ),
        migrations.DeleteModel(
            name='CountryPageRelatedSolution',
        ),
    ]
