# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0010_auto_20170905_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrypage',
            old_name='sub_title',
            new_name='subtitle',
        ),
    ]
