# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_auto_20170919_1636'),
        ('countries', '0012_auto_20170919_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrypage',
            name='solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='solutions.SolutionSnippet'),
        ),
    ]
