# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_auto_20170920_1024'),
        ('countries', '0015_auto_20170920_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryPageRelatedSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='countrypage',
            name='solution',
        ),
        migrations.AddField(
            model_name='countrypagerelatedsolution',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='countries.CountryPage'),
        ),
        migrations.AddField(
            model_name='countrypagerelatedsolution',
            name='solution_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country_solutions', to='solutions.SolutionPage'),
        ),
    ]
