# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('people', '0008_auto_20171030_1410'),
        ('countries', '0021_auto_20171030_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypagerelateddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='countrypagerelateddocument',
            name='page',
        ),
        migrations.RenameField(
            model_name='countrypage',
            old_name='subtitle',
            new_name='heading',
        ),
        migrations.RemoveField(
            model_name='countrypage',
            name='introduction',
        ),
        migrations.AddField(
            model_name='countrypage',
            name='hero_image',
            field=models.ForeignKey(blank=True, help_text='Hero Image to be used as full width feature image for page.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='partners_description',
            field=models.TextField(blank=True, help_text='Description text to appear below Partnerships heading for Partnership block.'),
        ),
        migrations.AddField(
            model_name='countrypage',
            name='person_category',
            field=models.ForeignKey(blank=True, help_text='Select a person category to display its team members.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.PersonCategory'),
        ),
        migrations.AlterField(
            model_name='countrypagerelatedpartner',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_partners', to='countries.CountryPage'),
        ),
        migrations.DeleteModel(
            name='CountryPageRelatedDocument',
        ),
    ]
