# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0023_auto_20171101_1229'),
        ('countries', '0022_auto_20171101_1026'),
    ]

    operations = [
    ]
