# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0024_merge_20171102_1124'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='countrypagerelatedsolution',
            name='page',
        ),
        migrations.RemoveField(
            model_name='countrypagerelatedsolution',
            name='solution_page',
        ),
        migrations.DeleteModel(
            name='CountryPageRelatedSolution',
        ),
    ]
