# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 15:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0035_auto_20171114_1544'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countrypage',
            old_name='heading',
            new_name='hero_strapline',
        ),
    ]
