# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0039_auto_20171121_1708'),
        ('countries', '0039_countrypage_social_title'),
    ]

    operations = [
    ]
