# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-10 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personpagepersoncategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_relationships', to='people.PersonCategory'),
        ),
    ]
