# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 15:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0010_auto_20171101_1229'),
        ('people', '0009_person_page_category'),
    ]

    operations = [
    ]
