# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0017_auto_20171109_1708'),
        ('people', '0017_auto_20171109_1541'),
    ]

    operations = [
    ]
