# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-10 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0018_merge_20171110_1142'),
        ('people', '0018_merge_20171110_1225'),
    ]

    operations = [
    ]
