# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-26 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('people', '0037_p1_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='personcategory',
            name='site',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Site', editable=False),
            preserve_default=False,
        ),
    ]
