# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-19 12:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
