# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 10:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20171114_1704'),
        ('home', '0004_auto_20171113_1058'),
    ]

    operations = [
    ]
