# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_merge_20171115_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Short Hero Video to show on top of page. Recommended size 12Mb or under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.CustomMedia'),
        ),
    ]
