# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 10:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_homepage_body'),
        ('home', '0008_auto_20171120_1614'),
    ]

    operations = [
    ]
