# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 15:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20171121_1112'),
        ('home', '0009_merge_20171121_1454'),
    ]

    operations = [
    ]
