# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 11:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_auto_20171121_1708'),
        ('home', '0011_homepage_social_title'),
    ]

    operations = [
    ]
