# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 13:51
from __future__ import unicode_literals

from django.db import migrations


def migrate_body_text(block):
    body_value = block['value']
    block["type"] = "body_text_new"
    block["value"] = {
        'body': body_value
    }
    return


def migrate_large_text(block):
    large_text_value = block['value']
    block["type"] = "large_text_new"
    block["value"] = {
        'body': large_text_value
    }
    return


def migrate_quote(block):
    quote_value = block['value']
    block["type"] = "quote_new"
    block["value"] = {
        'quotes': quote_value
    }
    return


def migrate_list(block):
    list_value = block['value']
    block["type"] = "list_block_new"
    block["value"] = {
        'list_block': list_value
    }
    return


def apply_migrations(block):
    if block['type'] == "body_text":
        migrate_body_text(block)
    if block['type'] == "large_text":
        migrate_large_text(block)
    if block['type'] == "quote":
        migrate_quote(block)
    if block['type'] == "list_block":
        migrate_list(block)
    return


def migrate_data(apps, schema_editor):
    ArticlePage = apps.get_model('articles', 'ArticlePage')
    HomePage = apps.get_model('home', 'HomePage')
    CountryPage = apps.get_model('countries', 'CountryPage')
    PersonPage = apps.get_model('people', 'PersonPage')
    SolutionPage = apps.get_model('solutions', 'SolutionPage')
    StandardPage = apps.get_model('standardpage', 'StandardPage')
    StandardIndex = apps.get_model('standardpage', 'StandardIndex')

    querysets = [
        ArticlePage.objects.all(), HomePage.objects.all(),
        CountryPage.objects.all(), PersonPage.objects.all(),
        SolutionPage.objects.all(), StandardPage.objects.all(),
        StandardIndex.objects.all()
    ]

    for queryset in querysets:
        for page in queryset:
            if hasattr(page, 'body'):
                for block in page.body.stream_data:
                    apply_migrations(block)
            if hasattr(page, 'biography'):
                for block in page.biography.stream_data:
                    apply_migrations(block)
            page.save()

    return


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20171214_1350'),
        ('standardpage', '0028_auto_20171214_1350'),
        ('people', '0028_auto_20171214_1350'),
        ('solutions', '0039_auto_20171214_1350'),
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
