# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-10 16:02
from __future__ import unicode_literals

import json

from django.db import migrations


def migrate_body_text(block):
    body_value = block['value']
    block["value"] = {
        'body': body_value
    }


def migrate_large_text(block):
    large_text_value = block['value']
    block["value"] = {
        'body': large_text_value
    }


def migrate_quote(block):
    quote_value = block['value']
    block["value"] = {
        'quotes': quote_value
    }


def migrate_list(block):
    list_value = block['value']
    block["value"] = {
        'list_block': list_value
    }


def apply_migrations(block):
    if block['type'] == "body_text":
        migrate_body_text(block)
    if block['type'] == "large_text":
        migrate_large_text(block)
    if block['type'] == "quote":
        migrate_quote(block)
    if block['type'] == "list_block":
        migrate_list(block)


def migrate_data(apps, schema_editor):
    ArticlePage = apps.get_model('articles', 'ArticlePage')
    HomePage = apps.get_model('home', 'HomePage')
    CountryPage = apps.get_model('countries', 'CountryPage')
    PersonPage = apps.get_model('people', 'PersonPage')
    SolutionPage = apps.get_model('solutions', 'SolutionPage')
    StandardPage = apps.get_model('standardpage', 'StandardPage')
    StandardIndex = apps.get_model('standardpage', 'StandardIndex')

    querysets = [
        ArticlePage.objects.all(), HomePage.objects.all(),
        CountryPage.objects.all(), PersonPage.objects.all(),
        SolutionPage.objects.all(), StandardPage.objects.all(),
        StandardIndex.objects.all()
    ]

    for queryset in querysets:
        for page in queryset:
            if hasattr(page, 'body'):
                for block in page.body.stream_data:
                    apply_migrations(block)
            if hasattr(page, 'biography'):
                for block in page.biography.stream_data:
                    apply_migrations(block)
            page.save()

            # Also migrate the revisions
            for revision in page.revisions.all():
                content = json.loads(revision.content_json)

                if 'body' in content:
                    body_content = json.loads(content['body'])

                    for block in body_content:
                        apply_migrations(block)

                    content['body'] = json.dumps(body_content)

                if 'biography' in content:
                    bio_content = json.loads(content['biography'])

                    for block in bio_content:
                        apply_migrations(block)

                    content['biography'] = json.dumps(bio_content)

                revision.content_json = json.dumps(content)
                revision.save()


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_streamfield_customisations'),
        ('articles', '0038_streamfield_customisations'),
        ('standardpage', '0028_streamfield_customisations'),
        ('countries', '0042_streamfield_customisations'),
        ('solutions', '0039_streamfield_customisations'),
        ('people', '0028_streamfield_customisations')
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
