# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 15:05
from __future__ import unicode_literals

from django.db import migrations


def migrate_body_text(block):
    block["type"] = "body_text"
    return


def migrate_large_text(block):
    block["type"] = "large_text"
    return


def migrate_quote(block):
    block["type"] = "quote"
    return


def migrate_list(block):
    block["type"] = "list_block"
    return


def apply_migrations(block):
    if block['type'] == "body_text_new":
        migrate_body_text(block)
    if block['type'] == "large_text_new":
        migrate_large_text(block)
    if block['type'] == "quote_new":
        migrate_quote(block)
    if block['type'] == "list_block_new":
        migrate_list(block)
    return


def migrate_data(apps, schema_editor):
    ArticlePage = apps.get_model('articles', 'ArticlePage')
    HomePage = apps.get_model('home', 'HomePage')
    CountryPage = apps.get_model('countries', 'CountryPage')
    PersonPage = apps.get_model('people', 'PersonPage')
    SolutionPage = apps.get_model('solutions', 'SolutionPage')
    StandardPage = apps.get_model('standardpage', 'StandardPage')
    StandardIndex = apps.get_model('standardpage', 'StandardIndex')

    querysets = [
        ArticlePage.objects.all(), HomePage.objects.all(),
        CountryPage.objects.all(), PersonPage.objects.all(),
        SolutionPage.objects.all(), StandardPage.objects.all(),
        StandardIndex.objects.all()
    ]

    for queryset in querysets:
        for page in queryset:
            if hasattr(page, 'body'):
                for block in page.body.stream_data:
                    apply_migrations(block)
            if hasattr(page, 'biography'):
                for block in page.biography.stream_data:
                    apply_migrations(block)
            page.save()

    return


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_add_old_block_name'),
        ('articles', '0039_auto_20171214_1500'),
        ('solutions', '0040_auto_20171214_1500'),
        ('countries', '0043_auto_20171214_1500'),
        ('people', '0029_auto_20171214_1500'),
        ('standardpage', '0029_auto_20171214_1500')
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
