# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-21 15:04

from __future__ import unicode_literals

from django.db import migrations
from django.utils.html import strip_tags


def migrate_carousel(block):
    value = block['value']
    new_block_value = {'slider_items': []}
    for i, slide in enumerate(value):
        new_values = {
            'image': slide['image'],
            'overview_title': slide['label'],
            'textbox_title': slide['title'],
            'textbox_text': strip_tags(slide['text']),
            'textbox_link': slide['link']
        }
        new_block_value['slider_items'].append(new_values)

    block["value"] = new_block_value
    block["type"] = "slider"
    return


def apply_migrations(block):
    if block['type'] == "carousel":
        migrate_carousel(block)
    return


def migrate_data(apps, schema_editor):
    ArticlePage = apps.get_model('articles', 'ArticlePage')
    HomePage = apps.get_model('home', 'HomePage')
    CountryPage = apps.get_model('countries', 'CountryPage')
    PersonPage = apps.get_model('people', 'PersonPage')
    SolutionPage = apps.get_model('solutions', 'SolutionPage')
    StandardPage = apps.get_model('standardpage', 'StandardPage')
    StandardIndex = apps.get_model('standardpage', 'StandardIndex')

    querysets = [
        ArticlePage.objects.all(), HomePage.objects.all(),
        CountryPage.objects.all(), PersonPage.objects.all(),
        SolutionPage.objects.all(), StandardPage.objects.all(),
        StandardIndex.objects.all()
    ]

    for queryset in querysets:
        for page in queryset:
            if hasattr(page, 'body'):
                for block in page.body.stream_data:
                    apply_migrations(block)
            if hasattr(page, 'biography'):
                for block in page.biography.stream_data:
                    apply_migrations(block)
            page.save()

    return


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_add_slider_block'),
        ('articles', '0041_add_slider_block'),
        ('standardpage', '0031_add_slider_block'),
        ('countries', '0045_add_slider_block'),
        ('solutions', '0042_add_slider_block'),
        ('people', '0031_add_slider_block')
    ]

    operations = [
        migrations.RunPython(migrate_data),
    ]
