# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_add_new_carousel_block_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecarouselitem',
            name='title_colour_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
