# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20180105_1521'),
        ('home', '0027_homepagecarouselitem_title_colour_hex'),
    ]

    operations = [
    ]
