# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20180105_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_strapline',
            field=models.TextField(blank=True, help_text='Shows text over the hero.', max_length=255),
        ),
    ]
