# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 15:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_p1_changes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='hero_strapline',
            field=models.TextField(blank=True, help_text='Shows text over the hero. If no strapline is entered, no page title will show.', max_length=255),
        ),
    ]
