# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 12:04
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_add_justify_to_richtext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='introduction',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, null=True),
        ),
    ]
