# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_introduction_field_rich_text'),
        ('home', '0033_home_featured_article'),
    ]

    operations = [
    ]
