# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0003_auto_20170811_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_title', models.CharField(blank=True, max_length=80)),
                ('solution_summary', models.CharField(blank=True, max_length=255)),
                ('solution_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='solutions.SolutionPage')),
            ],
        ),
    ]
