# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0004_solutionsnippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionsnippet',
            name='solution_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='solutions.SolutionPage'),
        ),
    ]
