# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-20 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0005_auto_20170919_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionsnippet',
            name='solution_page',
        ),
        migrations.DeleteModel(
            name='SolutionSnippet',
        ),
    ]
