# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-30 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('images', '0001_initial'),
        ('solutions', '0012_auto_20171023_1417'),
        ('people', '0007_auto_20171023_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='hero_fallback_image',
            field=models.ForeignKey(blank=True, help_text='Hero Image to be used as fallback for video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Hero Video. Recommended size 12Mb or under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='person_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.PersonCategory'),
        ),
    ]
