# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailmedia', '0003_copy_media_permissions_to_collections'),
        ('wagtailcore', '0040_page_draft_title'),
        ('images', '0001_initial'),
        ('partners', '0008_auto_20170921_1020'),
        ('people', '0009_person_page_category'),
        ('solutions', '0013_auto_20171030_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionPageRelatedPartner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ['sort_order'],
            },
        ),
        migrations.RemoveField(
            model_name='solutionpagerelateddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='solutionpagerelateddocument',
            name='page',
        ),
        migrations.RemoveField(
            model_name='solutionpagerelatedpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='solutionpagerelatedpage',
            name='source_page',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='summary',
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='hero_fallback_image',
            field=models.ForeignKey(blank=True, help_text='Hero Image to be used as fallback for video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Hero Video to show on top of page. Recommended size 12Mb or under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_page', to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='link_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='link_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='Logo for brands', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='person_category',
            field=models.ForeignKey(blank=True, help_text='Select a person category to display its team members.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='people.PersonCategory'),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='strapline',
            field=models.TextField(blank=True, max_length=80),
        ),
        migrations.DeleteModel(
            name='SolutionPageRelatedDocument',
        ),
        migrations.DeleteModel(
            name='SolutionPageRelatedPage',
        ),
        migrations.AddField(
            model_name='solutionpagerelatedpartner',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_partners', to='solutions.SolutionPage'),
        ),
        migrations.AddField(
            model_name='solutionpagerelatedpartner',
            name='solution_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solution_partners', to='partners.Partner'),
        ),
    ]
