# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 12:19
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0015_solutionpagerelatedpartner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionpagerelatedpartner',
            name='page',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_partners', to='solutions.SolutionPage'),
        ),
    ]
