# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0016_merge_20171101_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionpage',
            name='logo',
            field=models.ForeignKey(blank=True, help_text='The logo will show over the hero image.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='strapline',
            field=models.TextField(blank=True, help_text='The strapline will show over the hero image if a logo is not selected.', max_length=80),
        ),
    ]
