# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 10:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0017_auto_20171101_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
