# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0013_auto_20171030_1712'),
        ('solutions', '0017_auto_20171101_1625'),
    ]

    operations = [
    ]
