# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 09:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0018_merge_20171102_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Hero Video to show on top of page. Recommended size 12Mb or under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailmedia.Media'),
        ),
    ]
