# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-02 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('utils', '0005_auto_20171102_1407'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('solutions', '0019_auto_20171102_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionindex',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='solutionindex',
            name='social_image',
        ),
        migrations.DeleteModel(
            name='SolutionIndex',
        ),
    ]
