# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0029_auto_20171114_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionpage',
            old_name='logo',
            new_name='hero_logo',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='link_url',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='strapline',
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='hero_strapline',
            field=models.TextField(default='Strapline', help_text='The strapline will show over the hero image.', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='link_youtube',
            field=models.URLField(blank=True, help_text='Optional URL for a full length YouTube video goes here,                    which will open in a modal window.'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='hero_video',
            field=models.ForeignKey(blank=True, help_text='Short Hero Video to show on top of page. Recommended size 12Mb or under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.CustomMedia'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Optional page link as clickthrough for hero video.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
