# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-21 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0033_auto_20171117_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solutionpage',
            name='hero_strapline',
            field=models.TextField(blank=True, help_text='Shows text over the hero.', max_length=80),
        ),
    ]
