# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-22 15:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0034_solutionpage_social_title'),
        ('solutions', '0035_auto_20171121_1708'),
    ]

    operations = [
    ]
