# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-30 13:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0037_auto_20171127_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionpage',
            name='summary',
        ),
    ]
