# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-25 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0049_add_justify_to_richtext'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionpage',
            name='partners_description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='Description text to appear below Partnerships heading for Partnership block.', null=True),
        ),
        migrations.AddField(
            model_name='solutionpage',
            name='partners_title',
            field=models.CharField(blank=True, help_text='Title text to appear as Partnerships heading.', max_length=255, null=True),
        ),
    ]
