# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0050_partner_title_description'),
        ('solutions', '0051_solution_featured_article'),
    ]

    operations = [
    ]
