# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-06 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailsearchpromotions', '0002_capitalizeverbose'),
        ('images', '0001_initial'),
        ('utils', '0001_initial'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('partners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('external_link', models.URLField(blank=True)),
                ('link', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='partners.PartnerIndexPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='partnerpage',
            name='listing_image',
        ),
        migrations.RemoveField(
            model_name='partnerpage',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='partnerpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='partnerpage',
            name='social_image',
        ),
        migrations.RemoveField(
            model_name='partnerpagerelateddocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='partnerpagerelateddocument',
            name='page',
        ),
        migrations.RemoveField(
            model_name='partnerpagerelatedpage',
            name='page',
        ),
        migrations.RemoveField(
            model_name='partnerpagerelatedpage',
            name='source_page',
        ),
        migrations.DeleteModel(
            name='PartnerPage',
        ),
        migrations.DeleteModel(
            name='PartnerPageRelatedDocument',
        ),
        migrations.DeleteModel(
            name='PartnerPageRelatedPage',
        ),
    ]
