# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-11 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0002_auto_20170906_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
