# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-12 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0004_auto_20170911_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='title',
            field=models.CharField(default='Title', max_length=80),
            preserve_default=False,
        ),
    ]
