# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 08:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('partners', '0006_partnersnippet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnersnippet',
            old_name='solution_summary',
            new_name='link_text',
        ),
        migrations.RenameField(
            model_name='partnersnippet',
            old_name='partner_link',
            new_name='link_url',
        ),
        migrations.RemoveField(
            model_name='partnersnippet',
            name='partner_title',
        ),
        migrations.AddField(
            model_name='partnersnippet',
            name='link_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page'),
        ),
        migrations.AddField(
            model_name='partnersnippet',
            name='summary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='partnersnippet',
            name='title',
            field=models.CharField(default='Partner', max_length=8),
            preserve_default=False,
        ),
    ]
