# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-21 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0007_auto_20170921_0923'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnersnippet',
            name='link_page',
        ),
        migrations.DeleteModel(
            name='PartnerSnippet',
        ),
    ]
