# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-20 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0009_auto_20171114_1412'),
        ('partners', '0008_auto_20170921_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='show_on_index',
            field=models.BooleanField(default=True, verbose_name='Show on Partner Index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnerindexpage',
            name='call_to_action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='utils.CallToActionSnippet'),
        ),
    ]
