# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-14 15:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
        ('partners', '0011_auto_20171124_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerindexpage',
            name='introduction_customisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
        migrations.AddField(
            model_name='partnerindexpage',
            name='partners_customisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='images.CustomImage'),
        ),
    ]
