# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-17 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0012_partnercustomisableintroduction_partnercustomisablepartners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerindexpage',
            name='hero_strapline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
