# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-15 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0013_auto_20171214_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnercustomisableintroduction',
            name='heading_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='partnercustomisablepartners',
            name='heading_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
