# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-22 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0014_hero_strapline_helptext'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerindexpage',
            name='hero_strapline_hex',
            field=models.CharField(blank=True, help_text='Add valid hex to change colour of strapline.', max_length=7),
        ),
    ]
