# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-02-01 14:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0015_hero_strapline_customisation'),
        ('partners', '0014_introduction_field_rich_text'),
    ]

    operations = [
    ]
