# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-20 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_merge_20180201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='link_label',
            field=models.CharField(default='Learn more about ', max_length=255),
        ),
    ]
