# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-23 13:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_merge_20180201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='background_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='partner',
            name='text_hex',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
