# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-04-30 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partners', '0016_merge_20180201_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='block_background_hex',
            field=models.CharField(blank=True, help_text='Partner block background colour hex value', max_length=7, null=True, verbose_name='Background colour hex value'),
        ),
        migrations.AddField(
            model_name='partner',
            name='block_text_hex',
            field=models.CharField(blank=True, help_text='Partner block text colour hex value', max_length=7, null=True, verbose_name='Text colour hex value'),
        ),
    ]
