name: Publish Docker Image

on:
  push:
    branches: [ master, staging ]

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Add certificates
        run:
          apt-get update
          apt-get install ca-certificates
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v1
        with:
          push: true
          repository: girleffect/girleffect.org
          tag_with_ref: true
          tag_with_sha: true
          username: geautomation
          password: ${{ secrets.DOCKER_HUB_PASS }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
