# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-31 15:50
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('navigation', '0002_auto_20171120_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navigationsettings',
            name='footer_links',
            field=wagtail.wagtailcore.fields.StreamField((('item', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='primary_links',
            field=wagtail.wagtailcore.fields.StreamField((('item', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('sub_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False)), ('sub_items', wagtail.wagtailcore.blocks.ListBlock(wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False))), label='Sub-item')))), label='Sub-item')))))),), blank=True),
        ),
        migrations.AlterField(
            model_name='navigationsettings',
            name='secondary_links',
            field=wagtail.wagtailcore.fields.StreamField((('item', wagtail.wagtailcore.blocks.StructBlock((('page', wagtail.wagtailcore.blocks.PageChooserBlock(required=False)), ('external_url', wagtail.wagtailcore.blocks.URLBlock(required=False)), ('title', wagtail.wagtailcore.blocks.CharBlock(required=False))))),), blank=True),
        ),
    ]
